# Uncomment the next line to define a global platform for your project
platform :ios, ‘7.0’
use_frameworks!

target ‘BXHUD’ do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
 
  pod ‘MBProgressHUD’

end
